[project]
name = "karpathy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "matplotlib>=3.9.4",
    "requests>=2.32.5",
    "tiktoken>=0.12.0",
    "torch>=2.8.0",
    "transformers>=4.57.6",
]
